apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-openshift-ex
  name: nodejs-openshift-ex
  namespace: nodejs-demo
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodejs-openshift-ex
    deploymentconfig: nodejs-openshift-ex
  sessionAffinity: None
  type: ClusterIP
